In [ ]:
#Author: Austin Bearden
#Date Created: 4/16/2018
#Data Last Modified: 4/16/2018
#Project: imatrix

In [11]:
#Import block
import math
import numpy as np
import pandas as pd
from numpy.linalg import inv
from numpy.linalg import det
from numpy.linalg import eig

a = np.array([[1, 0, 4, 5], [0, 1, 4, 5], [0, 2, 4, 5], [2, 3, 4, 5]])
ainv = inv(np.matrix(a))

adet = det(np.matrix(a))

aeig = eig(np.matrix(a))

print("Inverse: ", ainv)
print("Determinant: ", adet)
print("Eignevalues: ", aeig)

Inverse:  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  5.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.60287970e+15  9.00719925e+15 -7.20575940e+15  1.80143985e+15]
 [ 2.88230376e+15 -7.20575940e+15  5.76460752e+15 -1.44115188e+15]]
Determinant:  2.775557561562889e-15
Eignevalues:  (array([ 1.20000000e+01, -2.00000000e+00,  1.00000000e+00, -9.18732368e-18]), matrix([[ 4.49403532e-01,  5.54700196e-01, -6.41617606e-01,
          1.09281222e-16],
        [ 4.49403532e-01,  5.54700196e-01,  2.78964176e-01,
          5.94216644e-16],
        [ 4.86853826e-01,  2.77350098e-01,  5.57928353e-01,
          7.80868809e-01],
        [ 5.99204709e-01, -5.54700196e-01, -4.46342682e-01,
         -6.24695048e-01]]))


In [7]:
#We need to output to a JSON file
#we need to allocate as meany row labels as there are rows
#So, the creation of the JSON file needs to be dynamic
# based on what matrix is input into application

In [8]:
#loop that goes over number of rows in array
# then puts key based on index value in char format

In [26]:
keys = []
rows = []
for i in range(len(a)):
    keys = np.append(keys, ('inv_' + str(i)))
    print (ainv[i])
    
print(keys)
print(rows)
my_df = pd.DataFrame(keys, rows)


[[0.  0.  0.  0.5]]
[[0. 0. 0. 0.]]
[[-3.60287970e+15  9.00719925e+15 -7.20575940e+15  1.80143985e+15]]
[[ 2.88230376e+15 -7.20575940e+15  5.76460752e+15 -1.44115188e+15]]
['inv_0' 'inv_1' 'inv_2' 'inv_3']
[]


ValueError: Shape of passed values is (1, 4), indices imply (1, 0)